version: "3.8"

services:
  jupyter-secure:
    build:
      context: .
    image: wahl-chat-backend:latest
    env_file:
      - .env
    environment:
      - JUPYTER_PORT=${JUPYTER_PORT:-8888}
      - JUPYTER_TOKEN=
        # - JUPYTER_PASSWORD_HASH=sha1:<CHANGEME>
    command: ["/app/scripts/start_jupyter.sh"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.civ-jupyter.rule=Host(`civ-jup.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.civ-jupyter.entrypoints=websecure"
      - "traefik.http.routers.civ-jupyter.tls=true"
      - "traefik.http.routers.civ-jupyter.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.civ-jupyter.loadbalancer.server.port=8888"
      - "traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK}"
    networks:
      - traefik-public
    volumes:
      - .:/app
    restart: unless-stopped

networks:
  traefik-public:
    name: ${TRAEFIK_PUBLIC_NETWORK}
    external: true
