version: "3.8"

services:
  civ-api:
    build:
      context: .
    image: civ-api:latest
    env_file:
      - .env
    restart: always
    networks:
      - feedarium-traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.civ-api.rule=Host(`civ-api.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.civ-api.entrypoints=websecure"
      - "traefik.http.routers.civ-api.tls=true"
      - "traefik.http.routers.civ-api.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.civ-api.loadbalancer.server.port=8080"
      - "traefik.docker.network=feedarium-traefik-public"

networks:
  feedarium-traefik-public:
    external: true
